apiVersion: apps/v1
kind: Deployment
metadata:
    name: capstone-create-update-deploy
    labels:
        app: capstone-create-update
spec:
    replicas: 1
    selector:
        matchLabels:
            app: capstone-create-update
    template:
        metadata:
            labels:
                app: capstone-create-update
        spec:
            containers:
            - name: capstone-create-update-container
              image: {image}:v{version}
              ports:
              - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-create-load-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-create-update
  ports:
      # By default the `targetPort` is set to the same value as the `port` field.
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-create-update-service ## name of the Service
spec:
  type: ClusterIP
  selector:
    app: capstone-create-update ## Serves as a label which should be refrenced in a Pod / Deployment manifest file
  ## department: ##same as above
  ports:
  - protocol: TCP ##The default is TCP
    port: 8081
